src/views/album.py
from flask import Blueprint, abort, escape, flash, jsonify, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from shared.auth import is_allowed, is_shared
from shared.common import get_user_id, load_items, load_album, ssl_required
from shared.util import get_logger, log_request
from modules.album import create_new_album, delete_one_album

logger = get_logger(__name__)
album_module = Blueprint('album', __name__)


@album_module.route('/user/<user_name>/album/<album_title>/view/')
@album_module.route('/user/<user_name>/album/<album_title>/<secret_part>/view/')
def index(user_name, album_title, secret_part=None):
    log_request(request, current_user)
    logger.debug('{View|Album} index(%s, %s, %s)', user_name, album_title, secret_part)

    shared = is_shared(current_user, user_name, album_title, secret_part)
    if not shared:
        return abort(404)

    env = {
        'module': '%s | %s' % (user_name, album_title),
        'header': False,
        'user': user_name,
        'album_title': album_title,
    }
    return render_template('album.html', **env)


@album_module.route('/user/<user_name>/album/<album_title>/view/get_items/')
@album_module.route('/user/<user_name>/album/<album_title>/<secret_part>/view/get_items/')
def get_items(user_name, album_title, secret_part=None):
    log_request(request, current_user)
    logger.debug('{View|Album} get_items(%s, %s, %s)', user_name, album_title, secret_part)

    if not is_shared(current_user, user_name, album_title, secret_part):
        return jsonify({})

    return load_items(user_name, album_title, only_visible=True)


@album_module.route('/user/<user_name>/album/<album_title>/view/get_album/')
@album_module.route('/user/<user_name>/album/<album_title>/<secret_part>/view/get_album/')
def get_album(user_name, album_title, secret_part=None):
    log_request(request, current_user)
    logger.debug('{View|Album} get_album(%s, %s, %s)', user_name, album_title, secret_part)

    if not is_shared(current_user, user_name, album_title, secret_part):
        return jsonify({})

    return load_album(current_user, user_name, album_title)


@album_module.route('/user/<user_name>/album/new', methods=['GET', 'POST'])
@login_required
@ssl_required
def new_album(user_name):
    log_request(request, current_user)
    logger.debug('{View|Album} new_album(%s)', user_name)

    if not is_allowed(current_user, user_name):
        return redirect(url_for('album.new_album', user_name=current_user.name))

    if request.method == 'POST':
        album_title = escape(request.form['album_title']) if 'album_title' in request.form else 'No title'
        album_desc = escape(request.form['album_desc']) if 'album_desc' in request.form else 'No description'
        result = create_new_album(get_user_id(user_name), album_title, album_desc)
        if result['success']:
            flash('Successfully created new album "%s"' % album_title, 'success')
            return redirect(url_for('user.index', user_name=user_name))
        else:
            flash('Can\'t create new album "%s"' % album_title, 'danger')

    env = {
        'module': 'Create new album',
        'header': True,
    }
    return render_template('album_new.html', **env)


@album_module.route('/user/<user_name>/album/<album_title>/delete/', methods=['GET', 'POST'])
@login_required
@ssl_required
def delete_album(user_name, album_title):
    log_request(request, current_user)
    logger.debug('{View|Album} delete_album(%s, %s)', user_name, album_title)

    if not is_allowed(current_user, user_name):
        return abort(404)

    if request.method == 'POST':
        result = delete_one_album(get_user_id(user_name), album_title)
        if result['success']:
            if result['success']:
                flash('Successfully deleted album "%s"' % album_title, 'success')
                return redirect(url_for('user.index', user_name=user_name))
            else:
                flash('Can\'t delete album "%s"' % album_title, 'danger')

    env = {
        'user_name': user_name,
        'album_title': album_title,
    }
    return render_template('album_delete.html', **env)

src/views/edit.py
import json

from flask import Blueprint, abort, jsonify, flash, render_template, redirect, request, url_for
from flask_login import current_user, login_required

from shared.auth import is_allowed
from shared.common import get_user_id, load_items, load_album, ssl_required
from shared.util import get_logger, log_request
from modules.edit import store_album, store_items, change_item_visibility, store_background, store_image, delete_one_item

logger = get_logger(__name__)
edit_module = Blueprint('edit', __name__)


@edit_module.route('/user/<user_name>/album/<album_title>/edit/')
@login_required
@ssl_required
def index(user_name, album_title):
    log_request(request, current_user)
    logger.debug('{View|Edit} index(%s, %s)', user_name, album_title)

    if not is_allowed(current_user, user_name):
        return abort(404)

    env = {
        'module': 'Edit %s/%s' % (user_name, album_title),
        'user_name': user_name,
        'album_title': album_title,
    }
    return render_template('edit.html', **env)


@edit_module.route('/user/<user_name>/album/<album_title>/edit/get_items/')
@login_required
@ssl_required
def get_items(user_name, album_title):
    log_request(request, current_user)
    logger.debug('{View|Edit} get_items(%s, %s)', user_name, album_title)

    if not is_allowed(current_user, user_name):
        return jsonify({})

    return load_items(user_name, album_title)


@edit_module.route('/user/<user_name>/album/<album_title>/edit/get_album/')
@login_required
@ssl_required
def get_album(user_name, album_title):
    log_request(request, current_user)
    logger.debug('{View|Edit} get_album(%s, %s)', user_name, album_title)

    if not is_allowed(current_user, user_name):
        return jsonify({})

    return load_album(current_user, user_name, album_title)


@edit_module.route('/user/<user_name>/album/<album_title>/edit/save_album/', methods=['POST'])
@login_required
@ssl_required
def save_album(user_name, album_title):
    log_request(request, current_user)
    logger.debug('{View|Edit} save_album(%s, %s)', user_name, album_title)

    if not is_allowed(current_user, user_name):
        return jsonify({'success': False})

    result = False
    if request.method == 'POST':
        data = request.get_json()
        del data['_csrf_token']
        result = store_album(user_name, album_title, data)

    return jsonify({'success': result})


@edit_module.route('/user/<user_name>/album/<album_title>/edit/save_items/', methods=['POST'])
@login_required
@ssl_required
def save_items(user_name, album_title):
    log_request(request, current_user)
    logger.debug('{View|Edit} save_items(%s, %s)', user_name, album_title)

    if not is_allowed(current_user, user_name):
        return jsonify({'success': False})

    result = False
    if request.method == 'POST':
        data = request.get_json()
        del data['_csrf_token']
        result = store_items(user_name, album_title, data)

    return jsonify({'success': result})


@edit_module.route('/user/<user_name>/album/<album_title>/edit/set-item-visibility/', methods=['GET', 'POST'])
@login_required
@ssl_required
def set_item_visibility(user_name, album_title):
    log_request(request, current_user)
    logger.debug('{View|Edit} set_item_visibility(%s, %s)', user_name, album_title)

    if not is_allowed(current_user, user_name):
        return abort(404)

    if request.method == 'POST':
        data = json.loads(request.data)
        id_item = data['item-id'] if 'item-id' in data else None
        item_visibility = data['item-visibility'] if 'item-visibility' in data else None
        result = change_item_visibility(user_name, album_title, id_item, item_visibility)
        return jsonify({'success': result})


@edit_module.route('/user/<user_name>/album/<album_title>/edit/upload_album_background/', methods=['GET', 'POST'])
@login_required
@ssl_required
def upload_background(user_name, album_title):
    log_request(request, current_user)
    logger.debug('{View|Edit} upload_background(%s, %s)', user_name, album_title)

    if not is_allowed(current_user, user_name):
        return abort(404)

    if request.method == 'POST':
        f = request.files['file']
        result = store_background(f, user_name, album_title)
        return jsonify({'success': result})


@edit_module.route('/user/<user_name>/album/<album_title>/edit/upload_item/', methods=['GET', 'POST'])
@login_required
@ssl_required
def upload_image(user_name, album_title):
    log_request(request, current_user)
    logger.debug('{View|Edit} upload_image(%s, %s)', user_name, album_title)

    if not is_allowed(current_user, user_name):
        return abort(404)

    if request.method == 'POST':
        f = request.files['file']
        result = store_image(f, user_name, album_title)
        return jsonify({'success': result})


@edit_module.route('/user/<user_name>/album/<album_title>/edit/delete/<id_item>', methods=['GET', 'POST'])
@login_required
@ssl_required
def delete_item(user_name, album_title, id_item):
    log_request(request, current_user)
    logger.debug('{View|Edit} delete_item(%s, %s, %s)', user_name, album_title, id_item)

    if not is_allowed(current_user, user_name):
        return abort(404)

    if request.method == 'POST':
        result = delete_one_item(get_user_id(user_name), album_title, id_item)
        if result['success']:
            if result['success']:
                flash('Successfully deleted item', 'success')
                return redirect(url_for('edit.index', user_name=user_name, album_title=album_title))
            else:
                flash('Can\'t delete item!', 'danger')

    env = {
        'user_name': user_name,
        'album_title': album_title,
        'id_item': id_item
    }
    return render_template('item_delete.html', **env)

src/views/index.py
from flask import Blueprint, escape, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_user, logout_user

from shared.common import ssl_required
import shared.db as db
from shared.util import get_logger, log_request

logger = get_logger(__name__)
index_module = Blueprint('index', __name__)


@index_module.route('/')
def index():
    log_request(request, current_user)
    logger.debug('{View|Index}')

    env = {
        'module': 'Home'
    }
    return render_template('index.html', **env)


@index_module.route('/login/', methods=['GET', 'POST'])
@ssl_required
def login():
    log_request(request, current_user)
    logger.debug('{View|Login}')

    if current_user.is_authenticated:
        return redirect(url_for('user.index', user_name=current_user.name))

    if request.method == 'POST':
        user_name = escape(request.form['user_name']) if 'user_name' in request.form else ''
        pw = escape(request.form['password']) if 'password' in request.form else ''
        u = db.User(user_name)
        u.set_authenticated(pw)
        if u.is_authenticated():
            login_user(u)
            return redirect(url_for('user.index', user_name=user_name))
        else:
            flash('Login failed!', 'danger')

    env = {
        'module': 'Login'
    }
    return render_template('login.html', **env)


@index_module.route('/logout/')
def logout():
    log_request(request, current_user)
    logger.debug('{View|Logout}')

    logout_user()
    return redirect(url_for('index.index'))

src/views/share.py
from flask import Blueprint, abort, escape, flash, render_template, redirect, request, url_for
from flask_login import current_user, login_required

from shared.auth import is_allowed
from shared.util import get_logger, log_request
from modules.share import share_album, get_share_type, get_share_types

logger = get_logger(__name__)
share_module = Blueprint('share', __name__)


@share_module.route('/user/<user_name>/album/<album_title>/share/', methods=['GET', 'POST'])
@login_required
def index(user_name, album_title):
    log_request(request, current_user)
    logger.debug('{View|Share} index(%s, %s)', user_name, album_title)

    if not is_allowed(current_user, user_name):
        return abort(404)

    if request.method == 'POST':
        share_type = escape(request.form['share_type']) if 'share_type' in request.form else 'Private'
        result = share_album(user_name, album_title, share_type)
        flash(result['msg'], 'info')
        return redirect(url_for('user.index', user_name=user_name))

    env = {
        'module': 'Share album',
        'title': album_title,
        'share_type': get_share_type(escape(user_name), escape(album_title)),
        'share_types': get_share_types()
    }
    return render_template('share.html', **env)

src/views/user.py
from flask import Blueprint, escape, render_template, request
from flask_login import current_user

from shared.common import is_current_user
from shared.util import get_logger, log_request
from modules.user import get_albums

logger = get_logger(__name__)
user_module = Blueprint('user', __name__)


@user_module.route('/user/<user_name>/')
def index(user_name):
    log_request(request, current_user)
    logger.debug('{View|User} index(%s)', user_name)

    albums = get_albums(user_name, current_user)

    env = {
        'module': 'User | %s' % escape(user_name),
        'is_current_user': is_current_user(user_name, current_user),
        'header': True,
        'user': user_name,
        'albums': albums,
    }
    return render_template('user.html', **env)

templates/album_new.html
{% extends "app.html" %}

{% block body %}

<div class="jumbotron">
  <div class="container">
    <h1>Create a new album</h1>
    <h4>All new albums will be private by default. You can change this
      later in the <b>Share</b> section.</h4>

    <form method="POST" class="form-inline">
      <input name="_csrf_token" type="hidden" value="{{ generate_csrf_token() }}">
      <div class="form-group">
        <label class="sr-only" for="album_title">Album name</label>
        <div class="input-group">
          <div class="input-group-addon">{{ current_user.name }} / </div>
          <input type="text" class="form-control" id="album_title" name="album_title" placeholder="my-cool-vacation-in-hawaii" autofocus>
        </div>
        <input type="text" class="form-control" id="album_desc" name="album_desc" placeholder="it was really cool">
      </div>
      <button type="submit" class="btn btn-primary">Create album</button>
    </form>
    <div class="errors">
      {% for error in errors %}
      <p><code>{{ error }}</code></p>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

templates/app.html
<!DOCTYPE html>
<html>
  <head>
    <title>travel-log | {{ module }}</title>
    <script type="text/javascript" src="{{ url_for('static', filename='lib/jquery/jquery.min.js') }}"></script>

    <link rel="stylesheet" href="{{ url_for('static', filename='lib/bootstrap/css/bootstrap.min.css') }}" type="text/css" />
    <script type="text/javascript" src="{{ url_for('static', filename='lib/bootstrap/js/bootstrap.min.js') }}"></script>

    <script type="text/javascript" src="{{ url_for('static', filename='app.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='app.css') }}" type="text/css" />
    {% block head %}{% endblock %}
  </head>
  <body>
    <div id="wrap">
      {% if header or (current_user.is_authenticated and not header == False) %}
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('index.index') }}"><span class="glyphicon glyphicon-picture"></span> travel-log</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{{ url_for('user.index', user_name='%s' % current_user.name)}}"><b>{{ current_user.name }}</b></a></li>
              {% if current_user.is_authenticated %}
              <li><a href="{{ url_for('index.logout') }}" class="btn btn-secondary btn-xs">Logout</a></li>
              {% else %}
              <li><a href="{{ url_for('index.login', _external=True, _scheme='https') }}" class="btn btn-secondary btn-xs">Login</a></li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
      {% endif %}

      {% block body %}{% endblock %}
    </div>

    <footer class="footer">
      <div class="container">
        <ul class="list-inline">
          <li class="text-muted"><a href="{{ url_for('index.about') }}">About</a></li>
          <li class="text-muted"><a href="{{ url_for('index.datenschutz') }}">Datenschutz</a></li>
          <li class="text-muted"><a href="{{ url_for('index.imprint') }}">Impressum</a></li>
        </ul>
      </div>
    </footer>
  </body>
</html>

templates/edit.html
{% extends "app.html" %}


{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='lib/osm/ol.css') }}" type="text/css" />
<script type="text/javascript" src="{{ url_for('static', filename='lib/osm/ol.js') }}"></script>

<link rel="stylesheet" href="{{ url_for('static', filename='lib/pickadate/classic.css') }}" type="text/css" />
<link rel="stylesheet" href="{{ url_for('static', filename='lib/pickadate/classic.date.css') }}" type="text/css" />
<link rel="stylesheet" href="{{ url_for('static', filename='lib/pickadate/classic.time.css') }}" type="text/css" />
<script type="text/javascript" src="{{ url_for('static', filename='lib/pickadate/picker.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='lib/pickadate/picker.date.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='lib/pickadate/picker.time.js') }}"></script>

<script type="text/javascript" src="{{ url_for('static', filename='map.js') }}"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='map.css') }}" type="text/css" />
<script type="text/javascript" src="{{ url_for('static', filename='edit.js') }}"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='edit.css') }}" type="text/css" />
{% endblock %}


{% block body %}

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div id="tile-header" class="tile panel panel-default">
        <div class="panel-heading">
          <div class="row">
            <div class="col-md-6">
              Editing album <b>{{ album_title }}</b>
              <input type="text" class="form-inline" id="album-description">
              <a href="{{ url_for('album.index', user_name='%s' % user_name, album_title='%s' % album_title) }}" target="_blank" title="Preview"><span class="glyphicon glyphicon-camera"></span></a>
              <a href="{{ url_for('share.index', user_name='%s' % user_name, album_title='%s' % album_title) }}" target="_blank" title="Edit share settings"><span class="glyphicon glyphicon-share"></span></a>
            </div>
            <div class="col-md-4">
            </div>
            <div class="col-md-2">
              <div id="last-saved"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <div class="row">
        <div class="col-md-12">
          <div id="tile-image-upload" class="tile panel panel-default">
            <div class="panel-heading">
              Image upload
            </div>
            <div class="panel-body">
              <form class="form-inline" style="margin-bottom: 1em;">
                <div class="form-group">
                  <label for="album-autoplay-delay">
                    Autoplay delay
                  </label>
                  <input type="number" min="1" max="30" class="form-control" id="album-autoplay-delay" name="album-autoplay-delay"/>
                </div>
              </form>

              <div id="thumbnail-list" class="row">
              </div>

              <div style="margin-top: 1em; float: right;">
                <form id="upload-file" action="" method="POST" enctype="multipart/form-data">
                  <input name="_csrf_token" type="hidden" value="{{ generate_csrf_token() }}">
                  <span id="item-upload-button" class="btn-file">
                    <span id="item-upload-button-text" class="btn btn-primary" data-loading-text="Uploading...">Browse</span>
                    <input id="image-file" name="file" type="file">
                  </span>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <div id="tile-background" class="tile panel panel-default">
            <div class="panel-heading">Album background</div>
            <div id="background-tabs" class="panel-body">
              <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#background-image-tab" aria-controls="background-image-tab" role="tab" data-toggle="tab">Image</a></li>
                <li role="presentation"><a href="#background-color-tab" aria-controls="background-color-tab" role="tab" data-toggle="tab">Color</a></li>
              </ul>

              <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="background-image-tab">
                  <form id="upload-background" action="" method="POST" enctype="multipart/form-data">
                    <input name="_csrf_token" type="hidden" value="{{ generate_csrf_token() }}">
                    <span id="album-background-upload-button" class="btn-file">
                      <span id="album-background-upload-button-text" class="btn btn-xs btn-success glyphicon glyphicon-picture" data-loading-text="Uploading..."> Upload</span>
                      <input id="background-image" name="file" type="file">
                    </span>
                  </form>
                </div>
                <div role="tabpanel" class="tab-pane" id="background-color-tab">
                  <span class="glyphicon glyphicon-pencil"></span> Choose
                  <input id="album-background-color" type="color" name="album-background-color">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div id="tile-main" class="tile panel panel-default">
        <div class="panel-heading">
          <div class="row">
            <div id="toggle-current-item-col" class="col-md-1">
              <a id="toggle-current-item" href="javascript:void(0);" class="btn btn-xs">
                <span class="glyphicon"></span>
              </a>
            </div>
            <div class="col-md-10">Current</div>
            <div id="delete-current-item-col" class="col-md-1">
              <a id="delete-current-item" href="javascript:void(0);" class="btn btn-xs btn-danger">
                <span class="glyphicon glyphicon-remove"></span>
              </a>
            </div>
          </div>
        </div>
        <div id="current-item" class="panel-body"></div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="row">
        <div class="col-md-12">
          <div id="tile-map" class="tile panel panel-default">
            <div class="panel-heading">Map</diV>
            <div id="map-panel" class="panel-body">
              <div id="map" style="height: 50px; width: 100%;"></div>
            </div>
          </diV>
        </div>
      </diV>

      <div class="row">
        <div class="col-md-12">
          <div id="tile-timestamp" class="tile panel panel-default">
            <div class="panel-heading">Time</div>
            <div class="panel-body">
              <input type="text" class="form-inline" id="item-date"/>
              <input type="text" class="form-inline" id="item-time"/>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <div id="tile-text" class="tile panel panel-default">
            <div class="panel-heading">Description</div>
            <div id="text-panel" class="panel-body">
              <textarea rows=5 class="form-control" id="item-description" placeholder="Your text"></textarea>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>


<div class="container">
</div>

{% endblock %}

templates/user.html
{% extends "app.html" %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='user.css') }}" type="text/css" />
{% endblock %}

{% block body %}

<div class="container">
  {% for msg in get_flashed_messages() %}
  <div class="well"><code>{{ msg }}</code></div>
  {% endfor %}

  <div class="jumbotron">
    <div class="row">
      <div class="col-md-2">
        <span class="glyphicon glyphicon-user" style="font-size: 4em;"></span>
      </div>
      {% if is_current_user %}
      <div class="col-md-8">
        <h2>Hello, {{ user }}</h2>
      </div>
      <div class="col-md-2">
        <a href="{{ url_for('album.new_album', user_name='%s' % user) }}" class="btn btn-success">Create a new album</a>
      </div>
      {% else %}
      <div class="col-md-10">
        <h3>{{ user }}</h3>
      </div>
      {% endif %}
    </div>
  </div>

  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-8">
      <h3>Albums</h3>
    </div>
  </div>

  {% for album in albums %}
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-8">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="row">
            <div class="col-md-2">
              <b>{{ album.album_title }}</b>
            </div>
            <div class="col-md-8">
            </div>
            <div class="col-md-2">
              {% if is_current_user %}
              <a style="float: right;" href="{{ url_for('share.index', user_name='%s' % user, album_title='%s' % album.album_title) }}">
                <span class="badge {{ album.share_type_name }}">{{ album.share_type_name }}
                  <span class="glyphicon glyphicon-share"></span>
                </span>
              </a>
              {% endif %}
            </div>
          </div>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-3">
              <div class="btn-group" role="group">
                {% if album.secret %}
                <a href="{{ url_for('album.index', user_name='%s' % user, album_title='%s' % album.album_title, secret_part='%s' % album.secret) }}" target="_blank" class="btn btn-xs btn-success">
                {% else %}
                <a href="{{ url_for('album.index', user_name='%s' % user, album_title='%s' % album.album_title) }}" target="_blank" class="btn btn-xs btn-success">
                {% endif %}
                  <span class="glyphicon glyphicon-camera"></span> View
                </a>
                {% if is_current_user %}
                <a href="{{ url_for('edit.index', user_name='%s' % user, album_title='%s' % album.album_title) }}" class="btn btn-xs btn-primary"><span class="glyphicon glyphicon-edit"></span> Edit</a>
                {% endif %}
              </div>
            </div>
            <div class="col-md-8">
              {{ album.album_desc }}
            </div>
            <div class="col-md-1">
              {% if is_current_user %}
              <a href="{{ url_for('album.delete_album', user_name='%s' % user, album_title='%s' % album.album_title) }}" class="btn btn-xs btn-danger"><span class="glyphicon glyphicon-remove"></span></a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}